feat: add dogs status DB and populate
zinizhu/ca-anmial-lovers pull request #9
Opened 2024-07-03 22:53 UTC by zubq

2024-07-03 23:04 UTC, zinizhu requested changes

2024-07-03 23:04 UTC, zinizhu commented on backend/src/db/constants.ts
> +    dog_id INT DEFAULT 0,
make `dog_id` required by removing the default value

2024-07-03 23:04 UTC, zinizhu commented on backend/src/db/constants.ts
> +    rescue_status TEXT,
Will an enum type be better? We can define a few status options

2024-07-03 23:04 UTC, zinizhu commented on backend/src/db/constants.ts
> +    adopter_foster_status TEXT,
Similarly, an enum type seems better

2024-07-03 23:04 UTC, zinizhu commented on backend/src/db/types.ts
> +  rescue_status: string;
Change to enum type

2024-07-03 23:04 UTC, zinizhu commented on backend/src/db/types.ts
> +  adopter_foster_status: string;
Change to enum type

2024-07-03 23:04 UTC, zinizhu commented on backend/src/db/db.ts
> +    console.log("Detect error during getDogByID: ", error);
```suggestion
    console.log("[getDogByID] error: ", error);
```

2024-07-03 23:42 UTC, zubq commented on backend/src/db/constants.ts
> +    dog_id INT DEFAULT 0,
Done

2024-07-03 23:42 UTC, zubq commented on backend/src/db/constants.ts
> +    rescue_status TEXT,
Done

2024-07-03 23:43 UTC, zubq commented on backend/src/db/constants.ts
> +    adopter_foster_status TEXT,
Done

2024-07-03 23:43 UTC, zubq commented on backend/src/db/types.ts
> +  rescue_status: string;
Done

2024-07-03 23:43 UTC, zubq commented on backend/src/db/types.ts
> +  adopter_foster_status: string;
Done

2024-07-03 23:43 UTC, zubq commented on backend/src/db/db.ts
> +    console.log("Detect error during getDogByID: ", error);
Done

2024-07-04 00:36 UTC, zinizhu commented on backend/src/db/constants.ts
> +    'commited'
```suggestion
    'committed'
```

2024-07-04 00:36 UTC, zinizhu commented on backend/src/db/constants.ts
> +    'in need',
```suggestion
    'in_need',
```

2024-07-04 00:37 UTC, zinizhu commented on backend/src/db/constants.ts
> +    'in contact',
```suggestion
    'in_contact',
```

2024-07-04 00:37 UTC, zinizhu commented on backend/src/db/constants.ts
> +    'in need',
```suggestion
    'in_need',
```

2024-07-04 00:37 UTC, zinizhu commented on backend/src/db/constants.ts
> +    'in contact',
```suggestion
    'in_contact',
```

2024-07-04 00:37 UTC, zinizhu commented on backend/src/db/constants.ts
> +    rescue_status: "in contact",
```suggestion
    rescue_status: "in_contact",
```

2024-07-04 00:38 UTC, zinizhu commented on backend/src/db/constants.ts
> +    adopter_foster_status: "in need",
```suggestion
    adopter_foster_status: "in_need",
```

2024-07-04 00:38 UTC, zinizhu commented on backend/src/db/constants.ts
> +    adopter_foster_status: "in contact",
```suggestion
    adopter_foster_status: "in_contact",
```

2024-07-04 00:38 UTC, zinizhu commented on backend/src/db/constants.ts
> +    adopter_foster_status: "commited",
```suggestion
    adopter_foster_status: "committed",
```

2024-07-04 00:41 UTC, zubq commented on backend/src/db/constants.ts
> +    'commited'
Done

2024-07-04 00:41 UTC, zubq commented on backend/src/db/constants.ts
> +    'in need',
Done

2024-07-04 00:41 UTC, zubq commented on backend/src/db/constants.ts
> +    'in contact',
Done

2024-07-04 00:42 UTC, zubq commented on backend/src/db/constants.ts
> +    'in need',
Done

2024-07-04 00:42 UTC, zubq commented on backend/src/db/constants.ts
> +    'in contact',
Done

2024-07-04 00:42 UTC, zubq commented on backend/src/db/constants.ts
> +    rescue_status: "in contact",
Done

2024-07-04 00:42 UTC, zubq commented on backend/src/db/constants.ts
> +    adopter_foster_status: "commited",
Done

2024-07-04 00:42 UTC, zubq commented on backend/src/db/constants.ts
> +    adopter_foster_status: "in contact",
Done

2024-07-04 00:42 UTC, zubq commented on backend/src/db/constants.ts
> +    adopter_foster_status: "in need",
Done

2024-07-04 00:45 UTC, zinizhu approved these changes
LGTM

2024-07-04 00:45 UTC, merged